bufferSize: 1024
pages:
- content: '            Welcome to our online survey about music perception and thank
    you very much for participating! <br> <br>             In this survey, we wish
    to understand the perception of the word brightness when talking about music.
    <br>             Brightness is widely used to describe the timbre attributes of
    a musical instrument, an opera singer&#39;s voice or any kind of sound. <br> <br>             With
    our study, we&#39;d like to find out how you perceive the brightness of multiple
    song snippets. <br> <br>             We will play you a reference song snippet
    and then ask you to rate the brightness of 4 other song snippets. <br>             Please
    use headphones to participate in this survey.             The survey will take
    approximately 10 minutes. <br> <br>            Please press <b> Next </b> below
    to proceed to the instructions page <br>             '
  id: generic1
  name: Brightness Perception Test
  type: generic
- content: '            You will be presented a reference sound and 4 potentially
    edited versions.             If any of the 4 conditions sounds less bright or
    more bright, you can indicate that by moving the slider down or up. <br> <br>             Although
    the slider is continuous, we&#39;ll assign all ratings to one of the five categories
    mentioned between the two enclosing markers. <br>             So, a rating of
    63 or 79 will both be assigned to the category <b> More Bright </b>.             Similarly,
    any rating between 0 to 19 will be assigned to the category <b> Least Bright </b>.
    <br> <br>            For each condition, your rating should be in comparison to
    the reference sound only. <br>             When a condition is played using the
    <b> Play </b> button, its slider becomes active and a rating can be selected.
    <br>             You can switch between the reference and condition as many times
    before selecting the rating. <br> <br>             If you perceive a song snippet
    as equally bright, that is no change from original, just set the slider at 50
    (same brightness). <br>             Please press <b> Next </b> below to proceed
    to the test <br>             '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: instruction1
  name: Instructions Page
  randomize: true
  reference: configs/resources/audio/experiment/Classical_GustavHolst_01_1/Classical_GustavHolst_01+0.000dB_sc1110hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Classical_GustavHolst_01_1/Classical_GustavHolst_01-2.00dB_sc933hz_scDelta-177hz.wav
    C2: configs/resources/audio/experiment/Classical_GustavHolst_01_1/Classical_GustavHolst_01+1.000dB_sc1222hz_scDelta+112hz.wav
    C3: configs/resources/audio/experiment/Classical_GustavHolst_01_1/Classical_GustavHolst_01-4.00dB_sc809hz_scDelta-301hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Grace_Jones_Snippet_1
  name: Grace_Jones_Snippet_1
  randomize: true
  reference: configs/resources/audio/experiment/Grace_Jones_Snippet_1/grace_jones_snippet+0.000dB_sc3808hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Grace_Jones_Snippet_1/grace_jones_snippet-1.00dB_sc3382hz_scDelta-425hz.wav
    C2: configs/resources/audio/experiment/Grace_Jones_Snippet_1/grace_jones_snippet-0.50dB_sc3589hz_scDelta-218hz.wav
    C3: configs/resources/audio/experiment/Grace_Jones_Snippet_1/grace_jones_snippet-3.00dB_sc2675hz_scDelta-1132hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Classical_RichardStrauss_1
  name: Classical_RichardStrauss_1
  randomize: true
  reference: configs/resources/audio/experiment/Classical_RichardStrauss_1/Classical_RichardStrauss+0.000dB_sc2986hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Classical_RichardStrauss_1/Classical_RichardStrauss+0.250dB_sc3058hz_scDelta+72hz.wav
    C2: configs/resources/audio/experiment/Classical_RichardStrauss_1/Classical_RichardStrauss-3.00dB_sc2245hz_scDelta-741hz.wav
    C3: configs/resources/audio/experiment/Classical_RichardStrauss_1/Classical_RichardStrauss+4.000dB_sc4224hz_scDelta+1238hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Lofi_01_2
  name: Lofi_01_2
  randomize: true
  reference: configs/resources/audio/experiment/Lofi_01_2/Lofi_01+0.000dB_sc3716hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Lofi_01_2/Lofi_01-2.00dB_sc2933hz_scDelta-782hz.wav
    C2: configs/resources/audio/experiment/Lofi_01_2/Lofi_01+2.000dB_sc4624hz_scDelta+909hz.wav
    C3: configs/resources/audio/experiment/Lofi_01_2/Lofi_01+0.750dB_sc4045hz_scDelta+329hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Techno_Kaf_01_1
  name: Techno_Kaf_01_1
  randomize: true
  reference: configs/resources/audio/experiment/Techno_Kaf_01_1/Techno_Kaf_01+0.000dB_sc2321hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Techno_Kaf_01_1/Techno_Kaf_01+0.250dB_sc2404hz_scDelta+83hz.wav
    C2: configs/resources/audio/experiment/Techno_Kaf_01_1/Techno_Kaf_01+2.000dB_sc3057hz_scDelta+736hz.wav
    C3: configs/resources/audio/experiment/Techno_Kaf_01_1/Techno_Kaf_01-1.00dB_sc2013hz_scDelta-308hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: HerbieHancock_Snippet_2
  name: HerbieHancock_Snippet_2
  randomize: true
  reference: configs/resources/audio/experiment/HerbieHancock_Snippet_2/herbie_hancock_snippet+0.000dB_sc5342hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/HerbieHancock_Snippet_2/herbie_hancock_snippet+0.250dB_sc5497hz_scDelta+155hz.wav
    C2: configs/resources/audio/experiment/HerbieHancock_Snippet_2/herbie_hancock_snippet-1.00dB_sc4747hz_scDelta-595hz.wav
    C3: configs/resources/audio/experiment/HerbieHancock_Snippet_2/herbie_hancock_snippet+0.500dB_sc5654hz_scDelta+312hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Techno_PolarInertia_2
  name: Techno_PolarInertia_2
  randomize: true
  reference: configs/resources/audio/experiment/Techno_PolarInertia_2/Techo_PolarInertia+0.000dB_sc5481hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Techno_PolarInertia_2/Techo_PolarInertia+4.000dB_sc7912hz_scDelta+2432hz.wav
    C2: configs/resources/audio/experiment/Techno_PolarInertia_2/Techo_PolarInertia+1.000dB_sc6103hz_scDelta+622hz.wav
    C3: configs/resources/audio/experiment/Techno_PolarInertia_2/Techo_PolarInertia-0.25dB_sc5327hz_scDelta-153hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Classical_GustavHolst_03_1
  name: Classical_GustavHolst_03_1
  randomize: true
  reference: configs/resources/audio/experiment/Classical_GustavHolst_03_1/Classical_GustavHolst_03+0.000dB_sc1949hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Classical_GustavHolst_03_1/Classical_GustavHolst_03+0.250dB_sc2001hz_scDelta+52hz.wav
    C2: configs/resources/audio/experiment/Classical_GustavHolst_03_1/Classical_GustavHolst_03+2.000dB_sc2393hz_scDelta+444hz.wav
    C3: configs/resources/audio/experiment/Classical_GustavHolst_03_1/Classical_GustavHolst_03+4.000dB_sc2878hz_scDelta+929hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Classical_GustavHolst_01_2
  name: Classical_GustavHolst_01_2
  randomize: true
  reference: configs/resources/audio/experiment/Classical_GustavHolst_01_2/Classical_GustavHolst_01+0.000dB_sc1110hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Classical_GustavHolst_01_2/Classical_GustavHolst_01+3.000dB_sc1498hz_scDelta+388hz.wav
    C2: configs/resources/audio/experiment/Classical_GustavHolst_01_2/Classical_GustavHolst_01-0.75dB_sc1036hz_scDelta-74hz.wav
    C3: configs/resources/audio/experiment/Classical_GustavHolst_01_2/Classical_GustavHolst_01+0.500dB_sc1164hz_scDelta+54hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Grace_Jones_Snippet_2
  name: Grace_Jones_Snippet_2
  randomize: true
  reference: configs/resources/audio/experiment/Grace_Jones_Snippet_2/grace_jones_snippet+0.000dB_sc3808hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Grace_Jones_Snippet_2/grace_jones_snippet+0.500dB_sc4037hz_scDelta+229hz.wav
    C2: configs/resources/audio/experiment/Grace_Jones_Snippet_2/grace_jones_snippet+4.000dB_sc5859hz_scDelta+2052hz.wav
    C3: configs/resources/audio/experiment/Grace_Jones_Snippet_2/grace_jones_snippet-2.00dB_sc3005hz_scDelta-803hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Classical_RichardStrauss_2
  name: Classical_RichardStrauss_2
  randomize: true
  reference: configs/resources/audio/experiment/Classical_RichardStrauss_2/Classical_RichardStrauss+0.000dB_sc2986hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Classical_RichardStrauss_2/Classical_RichardStrauss+2.000dB_sc3590hz_scDelta+604hz.wav
    C2: configs/resources/audio/experiment/Classical_RichardStrauss_2/Classical_RichardStrauss-1.00dB_sc2713hz_scDelta-273hz.wav
    C3: configs/resources/audio/experiment/Classical_RichardStrauss_2/Classical_RichardStrauss+1.000dB_sc3280hz_scDelta+294hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Lofi_01_1
  name: Lofi_01_1
  randomize: true
  reference: configs/resources/audio/experiment/Lofi_01_1/Lofi_01+0.000dB_sc3716hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Lofi_01_1/Lofi_01+1.000dB_sc4158hz_scDelta+443hz.wav
    C2: configs/resources/audio/experiment/Lofi_01_1/Lofi_01-0.50dB_sc3506hz_scDelta-210hz.wav
    C3: configs/resources/audio/experiment/Lofi_01_1/Lofi_01+4.000dB_sc5580hz_scDelta+1865hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Techno_Kaf_01_2
  name: Techno_Kaf_01_2
  randomize: true
  reference: configs/resources/audio/experiment/Techno_Kaf_01_2/Techno_Kaf_01+0.000dB_sc2321hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Techno_Kaf_01_2/Techno_Kaf_01-0.50dB_sc2162hz_scDelta-159hz.wav
    C2: configs/resources/audio/experiment/Techno_Kaf_01_2/Techno_Kaf_01-3.00dB_sc1518hz_scDelta-803hz.wav
    C3: configs/resources/audio/experiment/Techno_Kaf_01_2/Techno_Kaf_01+0.750dB_sc2579hz_scDelta+258hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: HerbieHancock_Snippet_1
  name: HerbieHancock_Snippet_1
  randomize: true
  reference: configs/resources/audio/experiment/HerbieHancock_Snippet_1/herbie_hancock_snippet+0.000dB_sc5342hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/HerbieHancock_Snippet_1/herbie_hancock_snippet-2.00dB_sc4199hz_scDelta-1143hz.wav
    C2: configs/resources/audio/experiment/HerbieHancock_Snippet_1/herbie_hancock_snippet+3.000dB_sc7286hz_scDelta+1943hz.wav
    C3: configs/resources/audio/experiment/HerbieHancock_Snippet_1/herbie_hancock_snippet-4.00dB_sc3272hz_scDelta-2070hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Classical_GustavHolst_03_2
  name: Classical_GustavHolst_03_2
  randomize: true
  reference: configs/resources/audio/experiment/Classical_GustavHolst_03_2/Classical_GustavHolst_03+0.000dB_sc1949hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Classical_GustavHolst_03_2/Classical_GustavHolst_03-0.50dB_sc1848hz_scDelta-100hz.wav
    C2: configs/resources/audio/experiment/Classical_GustavHolst_03_2/Classical_GustavHolst_03+3.000dB_sc2633hz_scDelta+684hz.wav
    C3: configs/resources/audio/experiment/Classical_GustavHolst_03_2/Classical_GustavHolst_03-1.00dB_sc1753hz_scDelta-196hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Techno_PolarInertia_1
  name: Techno_PolarInertia_1
  randomize: true
  reference: configs/resources/audio/experiment/Techno_PolarInertia_1/Techo_PolarInertia+0.000dB_sc5481hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Techno_PolarInertia_1/Techo_PolarInertia+0.250dB_sc5635hz_scDelta+155hz.wav
    C2: configs/resources/audio/experiment/Techno_PolarInertia_1/Techo_PolarInertia-0.75dB_sc5024hz_scDelta-456hz.wav
    C3: configs/resources/audio/experiment/Techno_PolarInertia_1/Techo_PolarInertia-2.00dB_sc4302hz_scDelta-1179hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: 'Rate the brightness of each stimuli compared to the reference '
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Classical_GustavHolst_01_1
  name: Classical_GustavHolst_01_1
  randomize: true
  reference: configs/resources/audio/experiment/Classical_GustavHolst_01_1/Classical_GustavHolst_01+0.000dB_sc1110hz_scDelta+0hz.wav
  showConditionNames: false
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/experiment/Classical_GustavHolst_01_1/Classical_GustavHolst_01-2.00dB_sc933hz_scDelta-177hz.wav
    C2: configs/resources/audio/experiment/Classical_GustavHolst_01_1/Classical_GustavHolst_01+1.000dB_sc1222hz_scDelta+112hz.wav
    C3: configs/resources/audio/experiment/Classical_GustavHolst_01_1/Classical_GustavHolst_01-4.00dB_sc809hz_scDelta-301hz.wav
  strict: false
  switchBack: true
  type: mushra
- content: Thank you for participating in the test!
  id: finish1
  name: Finish
  showResults: true
  type: finish
  writeResults: true
remoteService: service/write.php
showButtonPreviousPage: true
stopOnErrors: true
testId: mpcBrightness
testname: MPCBrightness
